// lib/health-config.js — Endpoint registry for Integra status page
'use strict';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CATEGORIES = ['blockchain', 'validators', 'apis', 'frontends', 'external'];
const ENVIRONMENTS = ['prod', 'dev', 'staging', 'release'];
const CHAIN_HALT_THRESHOLD_SECONDS = 60;

// Owner constants — real team members with email contacts
var OWNERS = {
  adam:   { name: 'Adam Boudj',  role: 'CTO / Infrastructure',    contact: 'adam@integralayer.com' },
  nawar:  { name: 'Nawar',       role: 'Backend Engineering',      contact: 'nawar@integralayer.com' },
  kalki:  { name: 'Kalki',       role: 'Full-Stack / Explorer',    contact: 'kalki@integralayer.com' },
  tara:   { name: 'Tara',        role: 'Frontend Engineering',     contact: 'tara@integralayer.com' },
  parth:  { name: 'Parth',       role: 'APIs / External Services', contact: 'parth@integralayer.com' },
};

// ---------------------------------------------------------------------------
// App groups (for minimal view)
// ---------------------------------------------------------------------------

const APP_GROUPS = [
  { id: 'dashboard', name: 'Dashboard', icon: '\uD83D\uDCCA', description: 'Portfolio management, staking, XP tracking, and asset management', endpoints: ['dashboard-prod', 'dashboard-dev', 'dashboard-api-prod', 'dashboard-api-dev', 'notification-api-prod', 'notification-api-dev', 'price-api'] },
  { id: 'explorer', name: 'Explorer', icon: '\uD83D\uDD0D', description: 'Block explorer for transactions, blocks, and validators', endpoints: ['explorer-mainnet', 'explorer-testnet', 'mainnet-cosmos-rpc', 'mainnet-cosmos-rest', 'testnet-cosmos-rpc', 'testnet-cosmos-rest'] },
  { id: 'city', name: 'City of Integra', icon: '\uD83C\uDFD9\uFE0F', description: 'Gamified city builder experience and game backend', endpoints: ['city-prod', 'city-dev', 'city-api-prod', 'city-api-dev'] },
  { id: 'portal', name: 'XP Portal', icon: '\u2B50', description: 'Points tracking, leaderboard, and rewards', endpoints: ['portal', 'absinthe-api'] },
  { id: 'blockchain', name: 'Blockchain Nodes', icon: '\u26D3\uFE0F', description: 'EVM and Cosmos RPC/REST nodes for mainnet and testnet', endpoints: ['mainnet-evm-rpc', 'testnet-evm-rpc'] },
  { id: 'validators', name: 'Validators', icon: '\u26A1', description: 'Mainnet validator nodes for block production and consensus', endpoints: ['validator-1', 'validator-2', 'validator-3', 'validator-adam'] },
  { id: 'sites', name: 'Websites & Docs', icon: '\uD83C\uDF10', description: 'Marketing website, documentation, whitepaper, and staking', endpoints: ['main-website', 'docs-site', 'whitepaper', 'staking', 'datastore'] },
  { id: 'standalone', name: 'Other APIs', icon: '\u2699\uFE0F', description: 'Supply data, file uploads, and utility endpoints', endpoints: ['supply-api', 'presign-api', 'upload-tracker-api'] },
  { id: 'external', name: 'External Services', icon: '\u2197\uFE0F', description: 'Third-party dependencies and integrations', endpoints: [] }, // filled dynamically below
];

// ---------------------------------------------------------------------------
// Endpoint registry
// ---------------------------------------------------------------------------

const ENDPOINTS = [
  // ── Blockchain (Mainnet — integra-1, EVM chain 26217) ──────────────────
  { id: 'mainnet-evm-rpc', name: 'Mainnet EVM RPC', category: 'blockchain', environment: 'prod', url: 'https://evm.integralayer.com', checkType: 'evm-rpc', timeout: 10000, enabled: true, expectedChainId: '0x6669', dependsOn: [], impacts: ['dashboard-api-prod'], impactDescription: 'Dashboard API loses EVM data — balances and transactions unavailable', description: 'EVM JSON-RPC for mainnet (chain 26217) — wallet balances, transactions, smart contracts', richDescription: 'The primary Ethereum-compatible JSON-RPC node for Integra mainnet (chain ID 26217), built on the Cosmos SDK EVM module. It serves all on-chain EVM data including wallet balances, token transfers, smart contract calls, and transaction receipts. The Dashboard API depends on this directly for portfolio valuations, staking position reads, and transaction history. If this endpoint goes down, the entire EVM data layer in the production dashboard becomes unavailable — users see stale balances and cannot submit transactions.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['EVM', 'Cosmos SDK'] },
  { id: 'mainnet-evm-ws', name: 'Mainnet EVM WebSocket', category: 'blockchain', environment: 'prod', url: 'wss://ws.integralayer.com', checkType: 'websocket', timeout: 10000, enabled: false, dependsOn: [], impacts: [], description: 'EVM WebSocket for mainnet — real-time event subscriptions', richDescription: 'WebSocket endpoint for real-time EVM event subscriptions on mainnet, enabling live monitoring of token transfers, contract events, and new blocks without polling. Currently disabled but planned for real-time dashboard features like live transaction feeds and instant balance updates. When activated, it will reduce latency for event-driven workflows from 30s polling intervals to sub-second push notifications.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['EVM', 'WebSocket'] },
  { id: 'mainnet-cosmos-rpc', name: 'Mainnet Cosmos RPC', category: 'blockchain', environment: 'prod', url: 'https://rpc.integralayer.com', checkType: 'cosmos-rpc', timeout: 10000, enabled: true, dependsOn: [], impacts: ['explorer-mainnet'], impactDescription: 'Mainnet explorer loses real-time block data', description: 'Cosmos RPC for mainnet — block data, transaction broadcasting, validator info', richDescription: 'The primary CometBFT RPC endpoint for the Integra mainnet, handling block queries, transaction broadcasting, validator set lookups, and consensus state. This is the backbone of the mainnet block explorer — it sources all real-time block data, transaction details, and validator information displayed to users. The explorer, staking interfaces, and governance tooling all query this node. Downtime means the explorer shows stale data and users cannot broadcast Cosmos-side transactions.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['Tendermint', 'CometBFT'] },
  { id: 'mainnet-cosmos-rpc2', name: 'Mainnet Cosmos RPC 2', category: 'blockchain', environment: 'prod', url: 'https://rpc2.integralayer.com', checkType: 'cosmos-rpc', timeout: 10000, enabled: false, dependsOn: [], impacts: [], description: 'Cosmos RPC backup for mainnet — failover node', richDescription: 'Backup CometBFT RPC node for mainnet, providing automatic failover if the primary RPC (rpc.integralayer.com) goes down or becomes unresponsive. Runs on a separate server from the primary node for geographic and infrastructure redundancy. Currently disabled in monitoring but kept synced and ready for emergency activation — can be promoted to primary within minutes by updating DNS records.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['Tendermint'] },
  { id: 'mainnet-cosmos-rest', name: 'Mainnet REST/LCD', category: 'blockchain', environment: 'prod', url: 'https://api.integralayer.com', checkType: 'cosmos-rest', timeout: 10000, enabled: true, dependsOn: [], impacts: ['explorer-mainnet'], impactDescription: 'Mainnet explorer loses validator and governance data', description: 'Cosmos REST/LCD for mainnet — governance, staking queries, account info', richDescription: 'The Cosmos REST (LCD) endpoint for mainnet, serving governance proposals, staking delegation data, account balances, validator sets, and distribution rewards via standard HTTP REST calls. The explorer depends on this heavily for validator detail pages, governance proposal displays, and account lookup features. External integrations (wallets, aggregators) also use this endpoint for IRL token balance queries. If down, governance and staking data disappears from all consumer applications.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['Cosmos SDK'] },

  // ── Blockchain (Testnet — ormos-1, EVM chain 26218) ────────────────────
  { id: 'testnet-evm-rpc', name: 'Testnet EVM RPC', category: 'blockchain', environment: 'dev', url: 'https://testnet-evm.integralayer.com', checkType: 'evm-rpc', timeout: 10000, enabled: true, expectedChainId: '0x666a', dependsOn: [], impacts: [], description: 'EVM JSON-RPC for testnet Ormos (chain 26218) — development & testing', richDescription: 'EVM JSON-RPC for the Ormos testnet (chain ID 26218), used by the development team for testing smart contract deployments, EVM transaction flows, and wallet integration before mainnet release. Nawar and Kalki rely on this for testing Dashboard and Explorer EVM features against real chain state. Downtime blocks the entire dev team from testing any EVM-related feature changes.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['EVM', 'Cosmos SDK'] },
  { id: 'testnet-cosmos-rpc', name: 'Testnet Cosmos RPC', category: 'blockchain', environment: 'dev', url: 'https://testnet-rpc.integralayer.com', checkType: 'cosmos-rpc', timeout: 10000, enabled: true, dependsOn: [], impacts: ['explorer-testnet'], impactDescription: 'Testnet explorer loses real-time block data', description: 'Cosmos RPC for testnet — development block data and testing', richDescription: 'CometBFT RPC for the Ormos testnet chain, providing block data, transaction broadcasting, and consensus state for development and QA. Powers the testnet block explorer with live chain data. The entire development workflow for Cosmos-side features depends on this — staking tests, governance simulations, and transaction verification all run against this endpoint. Outages halt QA cycles for features headed to mainnet.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['Tendermint'] },
  { id: 'testnet-cosmos-rest', name: 'Testnet REST/LCD', category: 'blockchain', environment: 'dev', url: 'https://testnet-api.integralayer.com', checkType: 'cosmos-rest', timeout: 10000, enabled: true, dependsOn: [], impacts: ['explorer-testnet'], impactDescription: 'Testnet explorer loses validator and governance data', description: 'Cosmos REST/LCD for testnet — development queries and testing', richDescription: 'Cosmos REST/LCD for the Ormos testnet, serving governance, staking, and account queries over HTTP for development. The testnet explorer depends on this for displaying validator and governance data during QA. Also used by the backend team for integration testing Dashboard API features against realistic chain data before promoting to production.', owner: OWNERS.adam, docsUrl: 'https://docs.integralayer.com/nodes', repoUrl: null, tags: ['Cosmos SDK'] },

  // ── Validators (mainnet) ───────────────────────────────────────────────
  { id: 'validator-1', name: 'Validator 1', category: 'validators', environment: 'prod', url: 'http://165.227.118.77:26657', checkType: 'cosmos-peer-check', peerIp: '3.92.110.107', publicRpc: 'https://rpc.integralayer.com', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Mainnet validator node (DigitalOcean) — block production and consensus', richDescription: 'Primary mainnet validator node hosted on DigitalOcean (NYC region), actively participating in CometBFT consensus and block production for the Integra network. This is one of four validators in the active set — its voting power directly influences block finality times. If this validator goes offline, the network loses ~25% of voting power, which degrades block production speed and could risk chain halts if combined with another validator failure. Monitored via peer connectivity checks against the public RPC.', owner: OWNERS.adam, docsUrl: null, repoUrl: null, tags: ['CometBFT', 'DigitalOcean'] },
  { id: 'validator-2', name: 'Validator 2', category: 'validators', environment: 'prod', url: 'http://159.65.168.118:26657', checkType: 'cosmos-peer-check', peerIp: '159.65.168.118', publicRpc: 'https://rpc.integralayer.com', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Mainnet validator node (DigitalOcean) — block production and consensus', richDescription: 'Second mainnet validator on DigitalOcean, contributing to BFT consensus and block finality for Integra mainnet. Provides redundancy in the validator set — if Validator 1 goes down, this node and others maintain consensus. Geographic separation from other nodes ensures the network withstands regional outages. Its consistent uptime is critical for maintaining the 2/3+ voting power threshold required for block production.', owner: OWNERS.adam, docsUrl: null, repoUrl: null, tags: ['CometBFT', 'DigitalOcean'] },
  { id: 'validator-3', name: 'Validator 3', category: 'validators', environment: 'prod', url: 'http://104.131.34.167:26657', checkType: 'cosmos-peer-check', peerIp: '104.131.34.167', publicRpc: 'https://rpc.integralayer.com', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Mainnet validator node (DigitalOcean) — block production and consensus', richDescription: 'Third mainnet validator on DigitalOcean, completing the infrastructure-managed validator trio. Participates in block signing, consensus voting, and maintains a full copy of chain state. Together with Validators 1 and 2, this node ensures the network has sufficient voting power for liveness even if one validator is temporarily down. Monitored for peer connectivity and block-signing participation.', owner: OWNERS.adam, docsUrl: null, repoUrl: null, tags: ['CometBFT', 'DigitalOcean'] },
  { id: 'validator-adam', name: "Adam's Node (AWS)", category: 'validators', environment: 'prod', url: 'http://adamboudj.integralayer.com:26657', checkType: 'cosmos-peer-check', peerIp: '3.92.110.107', publicRpc: 'https://rpc.integralayer.com', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: "Adam's validator node (AWS Singapore) — personal validator", richDescription: "Adam's personal validator node running on AWS EC2 in Singapore (ap-southeast-1), providing Asia-Pacific geographic diversity to the validator set. This is the only validator outside the DigitalOcean infrastructure, reducing single-provider risk. Bonded with 100 IRL tokens staked, actively signing blocks and earning staking rewards. Managed directly by Adam with separate SSH keys and monitoring — contact adam@integralayer.com for any issues with this specific node.", owner: OWNERS.adam, docsUrl: null, repoUrl: null, tags: ['CometBFT', 'AWS'] },

  // ── Backend APIs ───────────────────────────────────────────────────────
  { id: 'passport-api', name: 'Passport API', category: 'apis', environment: 'prod', url: 'https://passport-apis.integralayer.com/health/database', checkType: 'api-health', timeout: 10000, enabled: false, dependsOn: ['web3auth', 'google-oauth'], impacts: [], description: 'Passport authentication — wallet pregeneration, social login', richDescription: 'The authentication gateway for Integra, handling user signup and login via Web3Auth wallet pregeneration and Google OAuth social login. Built with NestJS and PostgreSQL, it creates non-custodial Integra wallets automatically when users sign up — no seed phrase management required. Depends on both Web3Auth (for wallet creation) and Google OAuth (for social login). Currently disabled pending the next onboarding flow release, but when active, it is the single entry point for all new user registrations.', owner: OWNERS.nawar, docsUrl: 'https://docs.integralayer.com', repoUrl: null, tags: ['NestJS', 'PostgreSQL'] },
  { id: 'dashboard-api-prod', name: 'Dashboard API', category: 'apis', environment: 'prod', url: 'https://dashboard-apis.integralayer.com', checkType: 'deep-health', healthUrl: 'https://dashboard-apis.integralayer.com/health', timeout: 10000, enabled: true, dependsOn: ['absinthe-api'], impacts: ['dashboard-prod'], impactDescription: 'Production dashboard fully unavailable', description: 'Dashboard backend — auth, assets, XP, staking, bulk imports (75+ endpoints)', richDescription: 'The primary backend powering the Integra Dashboard with 75+ REST API endpoints, built with NestJS, PostgreSQL, and JWT authentication. Handles portfolio management, staking position tracking, XP/points integration, asset management, bulk CSV imports, and notification preferences. The production Dashboard frontend is 100% dependent on this — if it goes down, users see a blank dashboard. Depends on the Absinthe XP API for points and leaderboard data. Deep health checks verify database connectivity and cache availability.', owner: OWNERS.nawar, docsUrl: 'https://docs.integralayer.com', repoUrl: 'https://github.com/Integra-layer/dashboard', tags: ['NestJS', 'PostgreSQL', 'JWT'] },
  { id: 'dashboard-api-dev', name: 'Dashboard API (Dev)', category: 'apis', environment: 'dev', url: 'https://dev-dashboard-apis.integralayer.com', checkType: 'deep-health', healthUrl: 'https://dev-dashboard-apis.integralayer.com/health', timeout: 10000, enabled: true, dependsOn: ['absinthe-api'], impacts: ['dashboard-dev'], impactDescription: 'Dev dashboard fully unavailable', description: 'Dashboard backend (dev) — same as prod, testnet networks', richDescription: 'Development instance of the Dashboard API, running the same NestJS codebase as production but connected to testnet blockchain networks and a separate dev database. Used by Nawar and the backend team for feature development, API testing, and QA validation before promoting changes to production. Also depends on Absinthe for XP features. If down, the dev Dashboard frontend is completely unusable, blocking frontend development and integration testing.', owner: OWNERS.nawar, docsUrl: 'https://docs.integralayer.com', repoUrl: 'https://github.com/Integra-layer/dashboard', tags: ['NestJS', 'PostgreSQL'] },
  { id: 'notification-api-prod', name: 'Notification API', category: 'apis', environment: 'prod', url: 'https://production-apis.integralayer.com', checkType: 'deep-health', healthUrl: 'https://production-apis.integralayer.com/health', timeout: 10000, enabled: true, dependsOn: [], impacts: ['dashboard-prod'], impactDescription: 'Dashboard notifications and alerts stop working', description: 'Push notifications and alerts for dashboard events', richDescription: 'Push notification service built with NestJS, responsible for delivering real-time alerts to Dashboard users for staking rewards, governance proposal updates, transaction confirmations, and account activity. Processes event triggers from the Dashboard API and dispatches notifications via push and in-app channels. If this service goes down, users miss time-sensitive alerts about their staking rewards and governance votes. Deep health checks monitor database and queue connectivity.', owner: OWNERS.nawar, docsUrl: null, repoUrl: null, tags: ['NestJS'] },
  { id: 'notification-api-dev', name: 'Notification API (Dev)', category: 'apis', environment: 'dev', url: 'https://develop-apis.integralayer.com', checkType: 'deep-health', healthUrl: 'https://develop-apis.integralayer.com/health', timeout: 10000, enabled: true, dependsOn: [], impacts: ['dashboard-dev'], impactDescription: 'Dev dashboard notifications stop working', description: 'Notification service (dev) — testing notifications', richDescription: 'Development instance of the Notification API, used for testing notification delivery logic, alert templates, and event trigger configurations before production deployment. Runs against a separate dev database and test notification channels. Essential for validating that new notification types render correctly and trigger at the right events. If down, the dev Dashboard loses notification functionality, blocking QA on notification-related features.', owner: OWNERS.nawar, docsUrl: null, repoUrl: null, tags: ['NestJS'] },
  { id: 'city-api-prod', name: 'City of Integra API', category: 'apis', environment: 'prod', url: 'https://ng6mpgxjz7.ap-south-1.awsapprunner.com', checkType: 'deep-health', healthUrl: 'https://ng6mpgxjz7.ap-south-1.awsapprunner.com/health', timeout: 10000, enabled: true, dependsOn: [], impacts: ['city-prod'], impactDescription: 'City builder game unavailable', description: 'City of Integra game backend — city builder logic, game state', richDescription: 'The game backend for City of Integra, a gamified city builder experience hosted on AWS App Runner in ap-south-1 (Mumbai). Manages all game state including building placement, resource generation, city progression, upgrade paths, and player inventories. The City Builder frontend is 100% dependent on this service — without it, the game is completely unplayable. Deep health checks verify database connectivity and game state consistency. Contact Kalki for game logic issues or Nawar for infrastructure/deployment concerns.', owner: OWNERS.kalki, docsUrl: null, repoUrl: 'https://github.com/Integra-layer/city', tags: ['AppRunner'] },
  { id: 'city-api-dev', name: 'City of Integra API (Dev)', category: 'apis', environment: 'dev', url: 'https://ygmwadph3x.ap-south-1.awsapprunner.com', checkType: 'deep-health', healthUrl: 'https://ygmwadph3x.ap-south-1.awsapprunner.com/health', timeout: 10000, enabled: true, dependsOn: [], impacts: ['city-dev'], impactDescription: 'Dev city builder unavailable', description: 'City of Integra game backend (dev)', richDescription: 'Development instance of the City of Integra game backend on AWS App Runner (Mumbai), used for testing new game mechanics, balance tuning, feature prototyping, and QA before production release. Runs against a separate dev database with test game state. If down, Kalki and the game team cannot test new features or validate bug fixes. Also used for load testing game logic before mainnet events.', owner: OWNERS.kalki, docsUrl: null, repoUrl: 'https://github.com/Integra-layer/city', tags: ['AppRunner'] },
  { id: 'supply-api', name: 'Circulating Supply', category: 'apis', environment: 'prod', url: 'https://supply.polytrade.finance', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Circulating token supply endpoint for exchanges/aggregators', richDescription: 'A lightweight API endpoint serving the current circulating supply of IRL tokens, consumed by cryptocurrency exchanges (for market cap calculations), data aggregators like CoinGecko and CoinMarketCap, and portfolio trackers. Returns a single number but has outsized importance — incorrect or unavailable supply data causes wrong market cap figures across all listing platforms. Hosted on Polytrade infrastructure (legacy domain). Contact Parth for supply calculation logic updates.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['API'] },
  { id: 'price-api', name: 'Pricing API', category: 'apis', environment: 'prod', url: 'https://price.api.polytrade.app', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: ['dashboard-prod'], impactDescription: 'Token prices missing from dashboard', description: 'Token pricing data for dashboard display', richDescription: 'Real-time token pricing API that aggregates IRL and related token prices from multiple sources, serving them to the Dashboard for portfolio valuations, staking reward estimates, and transaction value displays. If this endpoint goes down or returns stale data, users see incorrect portfolio totals and missing price charts in the production Dashboard. Hosted on Polytrade infrastructure. No external dependencies but impacts user confidence when prices appear stale or zero.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['API'] },
  { id: 'presign-api', name: 'Presigned URL API', category: 'apis', environment: 'prod', url: 'https://presign.api.polytrade.app', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Pre-signed URL generation for secure file uploads to S3', richDescription: 'Stateless microservice that generates time-limited pre-signed AWS S3 URLs for secure file uploads, used by the Dashboard for document uploads (KYC, title deeds) and the City Builder for asset uploads. Each URL expires after 15 minutes and is scoped to a specific S3 path. If down, all file upload workflows across the platform fail silently — users see upload buttons but files never reach S3. Contact Parth for S3 bucket configuration or CORS issues.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['AWS S3'] },
  { id: 'upload-tracker-api', name: 'Upload Tracker', category: 'apis', environment: 'prod', url: 'https://upload-tracker.api.polytrade.app', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Tracks file upload status and metadata', richDescription: 'Companion service to the Presigned URL API that tracks file upload progress, stores metadata (file size, type, upload timestamp), and confirms successful uploads to the requesting application. The Dashboard polls this service to show upload progress bars and confirm document receipt. If down, uploads still succeed (files reach S3) but the frontend shows perpetual "uploading" spinners and cannot confirm completion to the user.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['API'] },

  // ── Frontends & Explorers ──────────────────────────────────────────────
  { id: 'explorer-mainnet', name: 'Explorer (Mainnet)', category: 'frontends', environment: 'prod', url: 'https://explorer.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['mainnet-cosmos-rpc', 'mainnet-cosmos-rest'], impacts: [], description: 'Block explorer for mainnet — transactions, blocks, validators', richDescription: 'The mainnet block explorer built with Next.js and deployed on Vercel, providing transaction lookup, block browsing, validator profiles, governance proposal tracking, and account balance queries. This is the primary tool for anyone inspecting on-chain activity — validators checking their signing status, users verifying transactions, and developers debugging contract interactions. Depends on both the Cosmos RPC (for real-time blocks) and REST/LCD (for validator and governance data). Contact Kalki for explorer application issues.', owner: OWNERS.kalki, docsUrl: 'https://docs.integralayer.com', repoUrl: 'https://github.com/Integra-layer/explorer', tags: ['Next.js', 'Vercel'] },
  { id: 'explorer-testnet', name: 'Explorer (Testnet)', category: 'frontends', environment: 'dev', url: 'https://testnet.explorer.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['testnet-cosmos-rpc', 'testnet-cosmos-rest'], impacts: [], description: 'Block explorer for testnet — development testing', richDescription: 'Testnet block explorer for the Ormos chain, running the same Next.js codebase as the mainnet explorer but connected to testnet RPC and REST endpoints. Used daily by the dev team to verify test transactions, inspect testnet blocks, and validate governance features during QA. Depends on testnet Cosmos RPC and REST. If down, developers lose visibility into testnet chain activity and must resort to CLI queries for debugging.', owner: OWNERS.kalki, docsUrl: 'https://docs.integralayer.com', repoUrl: 'https://github.com/Integra-layer/explorer', tags: ['Next.js', 'Vercel'] },
  { id: 'docs-site', name: 'Documentation', category: 'frontends', environment: 'prod', url: 'https://docs.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['vercel'], impacts: [], description: 'Developer documentation and integration guides', richDescription: 'Developer documentation site built with Docusaurus and hosted on Vercel, containing API references, SDK integration guides, node operator runbooks, architecture overviews, and smart contract documentation. This is the first stop for external developers integrating with Integra and for internal team members referencing API specs. If down, developer onboarding stalls and the team loses access to canonical API documentation. Contact Tara for content updates or Vercel deployment issues.', owner: OWNERS.tara, docsUrl: 'https://docs.integralayer.com', repoUrl: null, tags: ['Docusaurus', 'Vercel'] },
  { id: 'main-website', name: 'Integra Website', category: 'frontends', environment: 'prod', url: 'https://integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['vercel'], impacts: [], description: 'Integra Layer marketing website', richDescription: 'The primary public-facing website for Integra Layer, built with Next.js and deployed on Vercel. Serves as the main entry point for potential users, investors, partners, and developers discovering the Integra ecosystem. Contains the product overview, team page, ecosystem links, blog, and investor materials. Downtime is highly visible — it is the first URL shared in pitches, press releases, and social media. Contact Tara for content or deployment.', owner: OWNERS.tara, docsUrl: null, repoUrl: null, tags: ['Next.js', 'Vercel'] },
  { id: 'dashboard-prod', name: 'Dashboard', category: 'frontends', environment: 'prod', url: 'https://dashboard.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['dashboard-api-prod'], impacts: [], description: 'Main dashboard — portfolio, staking, XP, assets, leaderboard', richDescription: 'The production Integra Dashboard — the flagship user-facing application built with React and deployed on Vercel. Provides portfolio management, staking delegation, XP tracking, asset management, leaderboard rankings, and notification preferences. This is where Integra users spend most of their time and is the single most important frontend service. Fully depends on the Dashboard API for all data. If the frontend itself is down (Vercel issue), users cannot access any platform features. Contact Nawar for API-related issues or Tara for frontend bugs.', owner: OWNERS.tara, docsUrl: 'https://docs.integralayer.com', repoUrl: 'https://github.com/Integra-layer/dashboard', tags: ['React', 'Vercel'] },
  { id: 'dashboard-dev', name: 'Dashboard (Dev)', category: 'frontends', environment: 'dev', url: 'https://dev-dashboard.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['dashboard-api-dev'], impacts: [], description: 'Dashboard (dev) — development and staging', richDescription: 'Development instance of the Dashboard frontend on Vercel, connected to the dev Dashboard API and testnet blockchain endpoints. Used by Tara and the frontend team for building and testing new UI features, validating design changes, and running E2E tests before production deployment. Also serves as the staging environment for stakeholder previews. If down, frontend development is blocked and the team cannot demo upcoming features.', owner: OWNERS.tara, docsUrl: 'https://docs.integralayer.com', repoUrl: 'https://github.com/Integra-layer/dashboard', tags: ['React', 'Vercel'] },
  { id: 'city-prod', name: 'City Builder', category: 'frontends', environment: 'prod', url: 'https://city.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['city-api-prod'], impacts: [], description: 'City of Integra — gamified city builder experience', richDescription: 'The production City of Integra web application — a gamified city builder where users construct and manage virtual cities to earn XP and rewards. Built with React and deployed on Vercel, it renders an interactive isometric city view with real-time building placement and resource management. Fully depends on the City API for all game logic and state persistence. If the frontend is down, users cannot access the game at all. Contact Kalki for game-related issues or Tara for frontend deployment.', owner: OWNERS.kalki, docsUrl: null, repoUrl: 'https://github.com/Integra-layer/city', tags: ['React', 'Vercel'] },
  { id: 'city-dev', name: 'City Builder (Dev)', category: 'frontends', environment: 'dev', url: 'https://dev-city.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['city-api-dev'], impacts: [], description: 'City of Integra (dev)', richDescription: 'Development instance of the City of Integra frontend on Vercel, used by Kalki for testing new game UI features, building animations, and UX improvements before production. Connected to the dev City API with test game state. Also used for playtesting new mechanics and balance changes with the team before releasing to users.', owner: OWNERS.kalki, docsUrl: null, repoUrl: 'https://github.com/Integra-layer/city', tags: ['React', 'Vercel'] },
  { id: 'whitepaper', name: 'Whitepaper', category: 'frontends', environment: 'prod', url: 'https://whitepaper.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'Technical whitepaper — protocol design and architecture', richDescription: 'The Integra Layer technical whitepaper, a static site on Vercel detailing the protocol design, CometBFT consensus mechanism, EVM module architecture, tokenomics (IRL supply, staking rewards, inflation), and network governance model. This document is referenced in investor due diligence, exchange listing applications, and developer onboarding. Downtime prevents potential investors and partners from accessing critical technical information. Contact Tara for content updates.', owner: OWNERS.tara, docsUrl: null, repoUrl: null, tags: ['Vercel'] },
  { id: 'portal', name: 'XP Portal', category: 'frontends', environment: 'prod', url: 'https://portal.integralayer.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: ['absinthe-api'], impacts: [], description: 'XP Portal — points tracking, leaderboard, rewards', richDescription: 'The XP Portal built with React on Vercel, where users track their accumulated points, view real-time leaderboard rankings, complete quests, and claim rewards. This is a key community engagement tool — active users check it daily for leaderboard position changes and new quest availability. Depends entirely on the Absinthe XP API for all points data and leaderboard calculations. If Absinthe is down, the portal shows stale or empty data. Contact Tara for frontend issues or Parth for Absinthe integration.', owner: OWNERS.tara, docsUrl: null, repoUrl: 'https://github.com/Integra-layer/portal', tags: ['React', 'Vercel'] },
  { id: 'staking', name: 'Staking App', category: 'frontends', environment: 'prod', url: 'https://staking.polytrade.finance', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: ['vercel'], impacts: [], description: 'Staking interface — delegate, undelegate, claim rewards', richDescription: 'The staking interface built with React on Vercel (Polytrade legacy domain), where users delegate IRL tokens to validators, manage their delegation positions, redelegate between validators, and claim accumulated staking rewards. This is critical for network security — it is the primary way token holders participate in consensus by staking. If down, users cannot delegate or claim rewards, potentially impacting validator economics and network security participation rates. Contact Tara for frontend issues.', owner: OWNERS.tara, docsUrl: null, repoUrl: null, tags: ['React', 'Vercel'] },
  { id: 'landing', name: 'Landing Page', category: 'frontends', environment: 'prod', url: 'https://get.polytrade.finance', checkType: 'http-get', timeout: 10000, enabled: false, dependsOn: ['vercel'], impacts: [], description: 'Legacy landing page (disabled)', richDescription: 'Legacy landing page from the Polytrade Finance era, currently disabled in monitoring. Traffic is being migrated to the new integralayer.com domain. Will be fully deprecated once DNS redirects are confirmed and all inbound links are updated. Keeping the endpoint registered for tracking purposes until deprecation is complete.', owner: OWNERS.tara, docsUrl: null, repoUrl: null, tags: ['Vercel'] },
  { id: 'datastore', name: 'NFT Datastore', category: 'frontends', environment: 'prod', url: 'https://datastore.polytrade.app', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'NFT datastore — asset metadata and media storage', richDescription: 'NFT metadata and media storage service hosted on Vercel, serving asset images, metadata JSON files, and collection information for NFT display across the Dashboard and marketplace features. Follows the ERC-721/1155 metadata standard so wallets and aggregators can resolve token URIs. If down, NFT thumbnails and metadata fail to load across the platform — users see broken images and missing asset names. Contact Tara for deployment or Parth for metadata schema changes.', owner: OWNERS.tara, docsUrl: null, repoUrl: null, tags: ['Vercel'] },

  // ── External Dependencies ──────────────────────────────────────────────
  { id: 'github-integra-layer', name: 'GitHub (Integra-layer)', category: 'external', environment: 'prod', url: 'https://api.github.com/orgs/Integra-layer', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'GitHub org — Integra-layer repositories', richDescription: 'The primary GitHub organization for Integra Layer, hosting all active repositories including the explorer, dashboard, city builder, validator tooling, and infrastructure-as-code. Monitored via the GitHub API to detect outages that would block CI/CD pipelines, code deployments, PR reviews, and developer collaboration. A GitHub outage halts all development velocity across the team. Contact Adam for org-level access issues.', owner: OWNERS.adam, docsUrl: null, repoUrl: 'https://github.com/Integra-layer', tags: ['GitHub'] },
  { id: 'github-polytrade', name: 'GitHub (polytrade-finance)', category: 'external', environment: 'prod', url: 'https://api.github.com/orgs/polytrade-finance', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], description: 'GitHub org — polytrade-finance repositories', richDescription: 'Legacy GitHub organization from the Polytrade Finance era, still hosting shared libraries, older smart contracts, and utility packages that some services depend on. Monitored to ensure CI/CD pipelines that pull from these repos continue to function. Being gradually migrated to the Integra-layer org. Contact Adam for access or migration questions.', owner: OWNERS.adam, docsUrl: null, repoUrl: 'https://github.com/polytrade-finance', tags: ['GitHub'] },
  { id: 'absinthe-api', name: 'Absinthe XP', category: 'external', environment: 'prod', url: 'https://gql3.absinthe.network', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: ['dashboard-api-prod', 'dashboard-api-dev', 'portal'], impactDescription: 'Dashboard XP features break, portal unusable', description: 'Absinthe Network — XP/points system, leaderboard sync', richDescription: "Absinthe Network's GraphQL API (gql3.absinthe.network) powering the entire XP/points ecosystem — point accumulation, leaderboard rankings, quest tracking, and reward eligibility calculations. This is a critical third-party dependency with wide blast radius: both Dashboard API instances (prod and dev) and the XP Portal depend on it. When Absinthe is down, XP features show errors across the Dashboard, the Portal displays empty leaderboards, and quest progress stops updating. Contact Parth for integration issues or escalation to the Absinthe team.", owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['GraphQL'] },
  { id: 'web3auth', name: 'Web3Auth', category: 'external', environment: 'prod', url: 'https://lookup.web3auth.io', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: ['passport-api'], impactDescription: 'Wallet pregeneration fails', description: 'Web3Auth — non-custodial wallet pregeneration, social login', richDescription: 'Web3Auth third-party service enabling non-custodial wallet pregeneration and social login for Integra users. When a user signs up via Google or email, Web3Auth generates an Integra wallet using MPC (multi-party computation) without the user managing a seed phrase. The Passport API depends on this for all new user registrations. If Web3Auth is down, new user onboarding fails completely — existing users can still log in via cached sessions but no new wallets can be created. Contact Parth for Web3Auth configuration or API key issues.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['OAuth'] },
  { id: 'openai-api', name: 'OpenAI', category: 'external', environment: 'prod', url: 'https://api.openai.com/v1/models', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], impactDescription: 'Title deed extraction fails', description: 'OpenAI — AI-powered title deed extraction and document processing', richDescription: 'OpenAI API integration (GPT-4 Vision) used in the Dashboard for AI-powered title deed extraction and document processing. When users upload property documents, the system uses GPT-4V to perform OCR, extract structured data (owner name, property details, valuation), and auto-populate form fields. If OpenAI is down, document uploads still succeed but automatic data extraction fails — users must manually enter all property information. Non-blocking but degrades UX significantly. Contact Parth for API key or model configuration.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['AI', 'GPT'] },
  { id: 'alchemy-rpc', name: 'Alchemy', category: 'external', environment: 'prod', url: 'https://eth-mainnet.g.alchemy.com', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: [], impactDescription: 'Webhook events stop, RPC fallback lost', description: 'Alchemy — blockchain RPC fallback, webhooks, event indexing', richDescription: "Alchemy's enterprise blockchain infrastructure providing fallback RPC access for Ethereum mainnet and EVM-compatible chains, plus webhook-based event indexing for token transfers and contract events. Acts as a reliability layer — if Integra's primary EVM RPC nodes are slow or unresponsive, services can failover to Alchemy endpoints. Also powers webhook-driven notifications for on-chain events. If Alchemy is down, the fallback RPC path is lost and webhook-based event processing stops. Contact Adam for Alchemy dashboard access or API key rotation.", owner: OWNERS.adam, docsUrl: null, repoUrl: null, tags: ['RPC', 'Webhooks'] },
  { id: 'twitter-api', name: 'Twitter/X', category: 'external', environment: 'prod', url: 'https://api.twitter.com/2', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: ['dashboard-prod'], impactDescription: 'Tweet display on dashboard fails', description: 'Twitter/X API — social media feed integration on dashboard', richDescription: 'Twitter/X API v2 integration for displaying the Integra social media feed on the Dashboard, showing recent announcements, community highlights, and ecosystem updates. While non-critical to core functionality, the social feed is prominently placed on the Dashboard home screen and its absence is visually noticeable to users. Frequent Twitter API rate limits or outages cause the feed section to show an empty state. Contact Tara for frontend display issues or Parth for API credential management.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['OAuth'] },
  { id: 'google-oauth', name: 'Google OAuth', category: 'external', environment: 'prod', url: 'https://accounts.google.com/.well-known/openid-configuration', checkType: 'http-json', timeout: 10000, enabled: true, dependsOn: [], impacts: ['passport-api'], impactDescription: 'Social login breaks', description: 'Google OAuth — social login for user authentication', richDescription: 'Google OAuth 2.0 / OpenID Connect endpoint used for social login authentication in the Passport API. When users click "Sign in with Google," the authentication flow hits this endpoint for token exchange and identity verification. If Google OAuth is down (extremely rare), all Google-based sign-ups and logins fail — users must wait or use alternative login methods. The Passport API checks the OIDC discovery document on startup to cache signing keys. Contact Parth for OAuth client configuration or redirect URI changes.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['OAuth', 'OIDC'] },
  { id: 'dicebear-api', name: 'DiceBear Avatars', category: 'external', environment: 'prod', url: 'https://api.dicebear.com/7.x/identicon/svg?seed=test', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: [], impacts: ['city-prod', 'city-dev'], impactDescription: 'City builder avatars break', description: 'DiceBear — procedural avatar generation for city builder', richDescription: 'DiceBear API v7 for procedural avatar generation in the City of Integra, creating unique identicon-style SVG avatars based on user wallet addresses or usernames. Both the production and dev City Builder frontends request avatars on-demand from this API. If DiceBear is down, avatar images fail to load and users see broken image placeholders in their city profiles and leaderboard entries. Low severity but visually noticeable. Contact Kalki for City Builder integration or consider caching avatars locally.', owner: OWNERS.kalki, docsUrl: null, repoUrl: null, tags: ['API'] },
  { id: 'walletconnect', name: 'WalletConnect', category: 'external', environment: 'prod', url: 'https://relay.walletconnect.com', checkType: 'http-reachable', timeout: 10000, enabled: true, dependsOn: [], impacts: ['dashboard-prod'], impactDescription: 'Wallet connections fail', description: 'WalletConnect — external wallet connection relay', richDescription: 'WalletConnect v2 relay server enabling external wallet connections (MetaMask, Trust Wallet, Rainbow, Coinbase Wallet, etc.) to the Integra Dashboard via QR code scanning or deep links. This is the bridge between mobile/browser wallets and the Dashboard — if the relay is down, users cannot connect their wallets to perform transactions, stake tokens, or sign messages. High impact because many users rely on external wallets rather than the embedded Passport wallet. Contact Tara for WalletConnect SDK integration or Parth for project ID configuration.', owner: OWNERS.parth, docsUrl: null, repoUrl: null, tags: ['WebSocket'] },
  { id: 'vercel', name: 'Vercel Platform', category: 'external', environment: 'prod', url: 'https://vercel.com', checkType: 'http-get', timeout: 10000, enabled: true, dependsOn: [], impacts: ['docs-site', 'main-website', 'staking', 'landing'], impactDescription: 'Docs, staking, landing go down', description: 'Vercel Platform — hosting for all frontend apps and docs', richDescription: 'Vercel platform-level availability monitoring — Vercel hosts all Integra frontend applications (Dashboard, Explorer, City Builder, Portal, Staking), documentation, whitepaper, and static sites. This is a platform-level dependency with the widest blast radius of any external service: if Vercel experiences an outage, the majority of user-facing Integra services go down simultaneously. Vercel provides edge CDN, serverless functions, and automatic deployments from GitHub. Contact Adam for Vercel team access or billing, or Tara for deployment configuration.', owner: OWNERS.adam, docsUrl: null, repoUrl: null, tags: ['CDN', 'Edge'] },
];

// ---------------------------------------------------------------------------
// Auto-fill external group with any external endpoints not claimed by others
// ---------------------------------------------------------------------------

(function() {
  var claimed = {};
  for (var g = 0; g < APP_GROUPS.length; g++) {
    if (APP_GROUPS[g].id === 'external') continue;
    var eps = APP_GROUPS[g].endpoints;
    for (var e = 0; e < eps.length; e++) claimed[eps[e]] = true;
  }
  var extGroup = APP_GROUPS.find(function(g) { return g.id === 'external'; });
  for (var i = 0; i < ENDPOINTS.length; i++) {
    if (ENDPOINTS[i].category === 'external' && !claimed[ENDPOINTS[i].id]) {
      extGroup.endpoints.push(ENDPOINTS[i].id);
    }
  }
})();

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

function getEndpoints(opts) {
  if (!opts) opts = {};
  var eps = ENDPOINTS;
  if (opts.enabledOnly !== false) eps = eps.filter(function(e) { return e.enabled; });
  if (opts.category) eps = eps.filter(function(e) { return e.category === opts.category; });
  if (opts.environment) eps = eps.filter(function(e) { return e.environment === opts.environment; });
  return eps;
}

function getEndpoint(id) {
  return ENDPOINTS.find(function(e) { return e.id === id; }) || null;
}

// ---------------------------------------------------------------------------
// Dependency graph
// ---------------------------------------------------------------------------

/**
 * Build adjacency lists for the dependency graph.
 * Returns { [id]: { dependsOn: [...], requiredBy: [...] } }
 */
function getDependencyGraph() {
  var graph = {};

  // Initialize every node
  for (var i = 0; i < ENDPOINTS.length; i++) {
    var ep = ENDPOINTS[i];
    if (!graph[ep.id]) graph[ep.id] = { dependsOn: [], requiredBy: [] };
  }

  // Build edges from dependsOn
  for (var j = 0; j < ENDPOINTS.length; j++) {
    var ep2 = ENDPOINTS[j];
    var deps = ep2.dependsOn || [];
    for (var k = 0; k < deps.length; k++) {
      var depId = deps[k];
      graph[ep2.id].dependsOn.push(depId);
      if (!graph[depId]) graph[depId] = { dependsOn: [], requiredBy: [] };
      graph[depId].requiredBy.push(ep2.id);
    }
  }

  // Build edges from impacts
  for (var m = 0; m < ENDPOINTS.length; m++) {
    var ep3 = ENDPOINTS[m];
    var imps = ep3.impacts || [];
    for (var n = 0; n < imps.length; n++) {
      var impId = imps[n];
      // Add to requiredBy if not already via dependsOn
      if (!graph[ep3.id]) graph[ep3.id] = { dependsOn: [], requiredBy: [] };
      if (graph[ep3.id].requiredBy.indexOf(impId) === -1) {
        graph[ep3.id].requiredBy.push(impId);
      }
      if (!graph[impId]) graph[impId] = { dependsOn: [], requiredBy: [] };
      if (graph[impId].dependsOn.indexOf(ep3.id) === -1) {
        graph[impId].dependsOn.push(ep3.id);
      }
    }
  }

  return graph;
}

/**
 * BFS: given a down endpoint ID, find all transitively impacted services.
 * Returns array of endpoint IDs that depend (directly or transitively) on downId.
 */
function getImpactedServices(downId) {
  var graph = getDependencyGraph();
  var visited = {};
  var queue = [downId];
  visited[downId] = true;
  var impacted = [];

  while (queue.length > 0) {
    var current = queue.shift();
    var node = graph[current];
    if (!node) continue;
    var dependents = node.requiredBy || [];
    for (var i = 0; i < dependents.length; i++) {
      var dep = dependents[i];
      if (!visited[dep]) {
        visited[dep] = true;
        impacted.push(dep);
        queue.push(dep);
      }
    }
  }

  return impacted;
}

module.exports = {
  ENDPOINTS: ENDPOINTS,
  CATEGORIES: CATEGORIES,
  ENVIRONMENTS: ENVIRONMENTS,
  CHAIN_HALT_THRESHOLD_SECONDS: CHAIN_HALT_THRESHOLD_SECONDS,
  APP_GROUPS: APP_GROUPS,
  OWNERS: OWNERS,
  getEndpoints: getEndpoints,
  getEndpoint: getEndpoint,
  getDependencyGraph: getDependencyGraph,
  getImpactedServices: getImpactedServices,
};
